before:
  hooks:
    - go mod tidy
builds:
  - main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{- .ProjectName }}_
      {{- if eq .Os "windows" }}{{- title "Windows" }}_
      {{- else if eq .Os "darwin" }}{{- title "Darwin" }}_
      {{- else if eq .Os "linux" }}{{- title "Linux" }}_
      {{- else }}{{ title .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
